# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Patch publisher info
      run: |
        cd ./i18n/vscode-language-pack-zh-hans
        sed "2s/vscode-language-pack-zh-hans/vscodium-language-pack-zh-cn/" -i package.json
        sed "3s/Code/Codium/" -i package.json
        sed "6s/MS-CEINTL/zhanghua/" -i package.json
        sed "9s_https://github.com/Microsoft/vscode-loc_https://github.com/zhanghua000/vscode-loc_" -i package.json
    - name: Publish to Open-vsx.org
      uses: HaaLeo/publish-vscode-extension@v0
      with:
        pat: ${{ secrets.OVSX_TOKEN }}
